---
abstract: ~
author:
  - 'Akzhan Abdulin, C<< <akzhan.abdulin at gmail.com> >>'
  - 'Akzhan Abdulin <akzhan.abdulin@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JavaScript-Console
no_index:
  directory:
    - inc
    - t
requires:
  JSON::XS: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=JavaScript-Console
  homepage: https://github.com/regru/JavaScript-Console
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git@github.com:regru/JavaScript-Console.git
version: 0.01
